#!/bin/bash

# ======================================================================================================================
# Constants Declaration
# ======================================================================================================================

# Specify the projects main path
PROJECTS_FOLDER="${HOME}/projetos/"

# Specify de packages names (also the folder names)
CHEMICAL_X="Chemical-X-SDKJS"
ALKHEMA_SDK="Alkhema-SDK"
ALKHEMA_TAM="Alkhema-TAM"
ALKHEMA_GOL="Alkhema-GOL"
ABSOLEM_TAM="Absolem-TAM"
JOCASTA_TAM="jocasta-tam"

# Specify the options available in the choices menu
MENU_OPTIONS=(
    $ALKHEMA_TAM "" off
    $ALKHEMA_GOL "" off
    $ABSOLEM_TAM "" off
    $JOCASTA_TAM "" off
)

# Specify de packages dependencies (must be declared in build order)
declare -A DEPENDENCIES=(
    [$ALKHEMA_TAM]="$CHEMICAL_X $ALKHEMA_SDK"
    [$ALKHEMA_GOL]="$CHEMICAL_X $ALKHEMA_SDK"
    [$ABSOLEM_TAM]="$CHEMICAL_X $ALKHEMA_SDK $ALKHEMA_TAM"
    [$JOCASTA_TAM]="$CHEMICAL_X $ALKHEMA_SDK $ALKHEMA_TAM"
)

# Stores de packages to build
declare -a BUILD_FLOW=()

# ======================================================================================================================
# Functions Declaration
# ======================================================================================================================

# Generates the build hash
function getBuildHash() {
    hash=$(tar -cf - node_modules dist yarn.lock | md5sum | awk '{print $1}')
    return $hash
}

# ======================================================================================================================
# Choices dialog
# ======================================================================================================================
cmd=(dialog --separate-output --checklist "Build-123 - Select projects to build:" 11 50 6)
choices=$("${cmd[@]}" "${MENU_OPTIONS[@]}" 2>&1 >/dev/tty)
clear

# Insert all dependencies on the build_flow array
for choice in $choices; do
    BUILD_FLOW+=("${DEPENDENCIES[$choice]}")
done

echo "${BUILD_FLOW[@]}"
