#!/bin/bash

# ======================================================================================================================
# Constants and variables declaration
# ======================================================================================================================

# Specify the projects main path
PROJECTS_FOLDER="${HOME}/projetos/"

# Specify de packages names (also the folder names)
CHEMICAL_X="Chemical-X-SDKJS"
ALKHEMA_SDK="Alkhema-SDK"
ALKHEMA_TAM="Alkhema-TAM"
ALKHEMA_GOL="Alkhema-GOL"
ABSOLEM_TAM="Absolem-TAM"
JOCASTA_TAM="jocasta-tam"

# Specify de packages dependencies (must be declared in build order and declare the self package)
declare -A DEPENDENCIES=(
    [$ALKHEMA_TAM]="$CHEMICAL_X $ALKHEMA_SDK"
    [$ALKHEMA_GOL]="$CHEMICAL_X $ALKHEMA_SDK $ALKHEMA_GOL"
    [$ABSOLEM_TAM]="$CHEMICAL_X $ALKHEMA_SDK $ALKHEMA_TAM $ABSOLEM_TAM"
    [$JOCASTA_TAM]="$CHEMICAL_X $ALKHEMA_SDK $ALKHEMA_TAM $JOCASTA_TAM"
)

# Specify the options available in the choices menu
MENU_OPTIONS=(
    $ALKHEMA_TAM "" off
    $ALKHEMA_GOL "" off
    $ABSOLEM_TAM "" off
    $JOCASTA_TAM "" off
)

# Stores de packages to build
BUILD_FLOW=""

# Color mapping
END='\n\033[0m'
WHITE='\033[1;37m'
RED='\033[1;31m'
GREEN='\033[1;36m'
BLUE='\033[1;34m'
YELLOW='\033[1;33m'
SECONDS=0

# ======================================================================================================================
# Functions declaration
# ======================================================================================================================

# Draw an horizontal line
function horizontalLine() {
    printf '%.s─' $(seq 1 $(tput cols))
}

# Show the header title
function showHeader() {
    horizontalLine
    printf "${RED}1${YELLOW}2${GREEN}3 ${WHITE}Builder"

    if [ "$1" ]; then
        printf ": $1"
    fi

    printf "${END}"

    horizontalLine
}

# Generates the build hash
function getBuildHash() {
    hash=$(tar -cf - dist yarn.lock | md5sum | awk '{print $1}')
    return $hash
}

# ======================================================================================================================
# Choices dialog
# ======================================================================================================================
cmd=(dialog --separate-output --checklist "Build-123 - Select projects to build:" 11 50 6)
choices=$("${cmd[@]}" "${MENU_OPTIONS[@]}" 2>&1 >/dev/tty)
clear

# Insert all dependencies on the BUILD_FLOW string
# Removes duplicate items
for choice in $choices; do
    BUILD_FLOW+="${DEPENDENCIES[$choice]} "
done

echo $BUILD_FLOW | awk -v RS="[ \n]+" '!n[$0]++'
